from typing import Annotated, TypedDict, List
from langgraph.graph.message import add_messages


class ResearchState(TypedDict):
    # The original topic/question the user wants researched
    topic: str

    # Used internally by the web searcher's ReAct loop (search tool calls etc.)
    messages: Annotated[list, add_messages]

    # List of sub-questions generated by the planner
    plan: List[str]

    # Raw search findings, one entry per sub-question researched
    search_results: List[str]

    # Condensed/clean version of search_results, written by the summarizer
    summary: str

    # The polished, final markdown report written by the writer
    final_report: str

    # The supervisor's routing decision: who should act next
    next: str

    # A follow-up instruction from the user, referencing the existing report
    # (e.g. "expand on the recycling section"). Empty/absent on a fresh topic.
    follow_up_instruction: str